services:
  - type: web
    name: advanced-media-access
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    nodeVersion: 20.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: advanced-media-access-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: YOUTUBE_DL_SKIP_DOWNLOAD
        value: "true"
      - key: YT_DLP_SKIP_DOWNLOAD
        value: "true"

databases:
  - name: advanced-media-access-db
    databaseName: advanced_media_access
    user: advanced_media_access_user
    ipAllowList: []  # Only allow internal connections